    
UPDATE temp_table_dsw_mod8
SET KOSTENFEHLTEILE =  
    NVL(GESAMTFEHLTEILE, 0) * NVL(EINZELPREIS_BRUTTO, 0) 

UPDATE temp_table_dsw_mod8
SET WERT_PRO_FZG =  
    NVL(DSW_MENGE_1AUFTR, 0) * NVL(EINZELPREIS_BRUTTO, 0) 

UPDATE temp_table_dsw_mod8
SET WERT_REST_LAGERBESTAND =  
    NVL(REST_LAGER_64, 0) * NVL(EINZELPREIS_BRUTTO, 0) 

UPDATE temp_table_dsw_mod8
SET WERT_ANFANGS_LAGERBESTAND =  
    NVL(LAGERBESTAND, 0) * NVL(EINZELPREIS_BRUTTO, 0)
